spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sajilni   # if Spring runs on host
    username: postgres
    password: AhmadSajidSura2003
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    properties.mail.smtp.auth: false
    properties.mail.smtp.starttls.enable: false
  redis:
    host: localhost
    port: 6379

app:
  otp:
    length: 6
    ttl-minutes: 30
    type: NUMERIC
    name: "Sajilni"
    website: "https://sajilni.com"
    support:
        email: "support@sajilni.com"
  jwt:

    secret: "6513304bfbecff49289dee08cf1b79163ed2641923144dd3545966ed66c9014ba5db3445a10979682808b50897310d26587a64fb37a85bc51c30f00d9dcf004d" #Certificate
    expirationMs: 30m    # 30 minutes
    issuer: "127.0.0.1" # Localhost

  server:
    port: 8080
  mail:
    host: smtp.gmail.com
    port: 465
    username: notifciation.twinscode@gmail.com
    password: jdlv jzff jwqs kjur
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            protocols: TLSv1.2
          starttls:
            enable: false
            required: false
